ARG NODE_VERSION
FROM node:${NODE_VERSION}

WORKDIR /usr/src/app
USER node

# COPY package*.json ./

# RUN npm install --location=global npm
# RUN npm install
# RUN vue upgrade


## Ressource pour installer un nouveau projet Nuxt3
# npm install -g @vue/cli
# vue create .
# vue upgrade